# Generated by Django 6.0.5 on 2026-05-22 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compras', '0002_initial'),
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaporcobrar',
            name='venta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_cobrar', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='abonocuentacobrar',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.cuentaporcobrar'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='compra',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cuenta_por_pagar', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_por_pagar', to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='cuentaporpagar',
            name='registrada_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_pagar_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='abonocuentapagar',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonos', to='core.cuentaporpagar'),
        ),
    ]
