# Generated by Django 4.2.16 on 2026-06-05 17:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonocuentacobrar',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='abonocuentapagar',
            name='tasa_bcv',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=12),
        ),
    ]
