# Generated by Django 4.2.16 on 2026-06-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_abonocuentacobrar_tasa_bcv_abonocuentapagar_tasa_bcv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='accion',
            field=models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('login_fallido', 'Intento de login fallido'), ('alta_usuario', 'Alta de usuario'), ('baja_usuario', 'Baja de usuario'), ('edicion_usuario', 'Edición de usuario'), ('crear_producto', 'Producto creado'), ('editar_producto', 'Producto editado'), ('ajuste_stock', 'Ajuste manual de stock'), ('crear_compra', 'Orden de compra creada'), ('aprobar_compra', 'Orden de compra aprobada'), ('rechazar_compra', 'Orden de compra rechazada'), ('cancelar_compra', 'Orden de compra cancelada'), ('recibir_compra', 'Recepción de mercancía registrada'), ('pago_proveedor', 'Pago a proveedor registrado'), ('crear_venta', 'Venta procesada'), ('cancelar_venta', 'Venta cancelada'), ('pago_cliente', 'Pago de cliente registrado'), ('tasa_bcv', 'Tasa BCV actualizada')], max_length=30),
        ),
    ]
