# Generated by Django 6.0.5 on 2026-05-22 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('metodo_pago', models.CharField(choices=[('punto', 'Punto de venta'), ('pago_movil', 'Pago móvil'), ('biopago', 'BioPago'), ('mixto', 'Mixto'), ('credito', 'A crédito / Fiado')], max_length=15)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, verbose_name='Referencia de pago')),
                ('estado', models.CharField(choices=[('procesada', 'Procesada'), ('a_credito', 'A crédito / Fiado'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='procesada', max_length=15)),
                ('fecha_estimada_pago', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de pago (crédito)')),
                ('subtotal_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_bs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tasa_bcv_momento', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_factura', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número de factura')),
                ('observacion', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.cliente')),
                ('empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-fecha', '-hora'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de venta',
            },
        ),
    ]
