# Generated by Django 6.0.5 on 2026-05-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_estimada', models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega')),
                ('fecha_recepcion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha real de recepción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobada', 'Aprobada'), ('recibida', 'Recibida'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15)),
                ('modalidad_pago', models.CharField(blank=True, choices=[('contado', 'Contado'), ('credito', 'Crédito')], max_length=10, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha límite de pago')),
                ('referencia_documento', models.CharField(blank=True, max_length=100, verbose_name='Referencia / Nro. documento')),
                ('numero_referencia', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Referencia interna')),
                ('observacion', models.TextField(blank=True)),
                ('motivo_rechazo', models.TextField(blank=True)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
            ],
            options={
                'verbose_name': 'Orden de compra',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_pedida', models.IntegerField()),
                ('cantidad_recibida', models.IntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
            ],
        ),
    ]
